name: 'nestjs-api'

services:
  db:
    image: postgres:14-alpine3.20
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    container_name: postgres
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./database/docker-entrypoint-initdb:/docker-entrypoint-initdb.d
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - /app/node_modules
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      - db
    networks:
      - backend

networks:
  backend: